import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBezierCurve,
  faCheck,
  faChevronLeft,
  faCity,
  faClock,
  faCompress,
  faDatabase,
  faExpand,
  faEyeDropper,
  faFire,
  faGlobe,
  faHeart as fasHeart,
  faInfoCircle,
  faPlus,
  faTachometerAlt,
  faTimes,
  faTimesCircle,
  faSave,
  faSearch,
  faStar as fasStar,
  faSync,
  faTrash,
  faUndo,
  faUser,
  faUsers,
  faUsersCog,
  faUserShield
} from '@fortawesome/free-solid-svg-icons';
import {
  faCheckSquare,
  faHeart as farHeart,
  faStar as farStar,
  faSquare
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faBezierCurve,
  faCheck,
  faCheckSquare,
  faChevronLeft,
  faCity,
  faClock,
  faCompress,
  faDatabase,
  faExpand,
  faEyeDropper,
  faFire,
  faGlobe,
  faInfoCircle,
  fasHeart,
  farHeart,
  faPlus,
  faSave,
  faSearch,
  faSquare,
  fasStar,
  farStar,
  faSync,
  faTachometerAlt,
  faTimes,
  faTimesCircle,
  faTrash,
  faUndo,
  faUser,
  faUsers,
  faUsersCog,
  faUserShield
);

export default library;
