import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBezierCurve,
  faCheck,
  faTimesCircle,
  faMinusCircle,
  faCheckCircle,
  faCheckSquare as fasCheckSquare,
  faChevronLeft,
  faCity,
  faClock,
  faCompress,
  faDatabase,
  faExpand,
  faEyeDropper,
  faFire,
  faGlobe,
  faHeart as fasHeart,
  faInfoCircle,
  faPlus,
  faSave,
  faSearch,
  faStar as fasStar,
  faSync,
  faTachometerAlt,
  faTimes,
  faToggleOff,
  faToggleOn,
  faTrash,
  faUndo,
  faUser,
  faUsers,
  faUsersCog,
  faUserShield,
  faList,
  faTh,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleLeft,
  faAngleRight
} from '@fortawesome/free-solid-svg-icons';
import {
  faCheckSquare,
  faHeart as farHeart,
  faStar as farStar,
  faSquare
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faBezierCurve,
  faCheck,
  faCheckSquare,
  faChevronLeft,
  faCity,
  faClock,
  faCompress,
  faDatabase,
  faExpand,
  faEyeDropper,
  faFire,
  faGlobe,
  faInfoCircle,
  faTimesCircle,
  faMinusCircle,
  faCheckCircle,
  fasHeart,
  faPlus,
  farHeart,
  farStar,
  faSave,
  fasCheckSquare,
  faSearch,
  fasHeart,
  faSquare,
  fasStar,
  faSync,
  faTachometerAlt,
  faTimes,
  faToggleOff,
  faToggleOn,
  faTrash,
  faUndo,
  faUser,
  faUsers,
  faUsersCog,
  faUserShield,
  faList,
  faTh,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleRight,
  faAngleLeft
);

export default library;
